title: Gettysburg Youth Soccer Club
message: There is a fundraiser on November 13th to support GYSC. Please read the information on our <a href="www.gettysburgyouthsoccer.org/fundraisers">fundraiser</a>page.
#build config
server: true
auto: true
markdown: rdiscount 
