title: Gettysburg Youth Soccer Club
message: The Gettysburg Youth Soccer Club (GYSC) will hold tryouts for the Fall 2013/Spring 2014 season the week of April 29th. Additional information about the tryouts is available on GYSC's website under <a href="http://www.gettysburgyouthsoccer.org/tryouts">Tryouts</a>. Tryouts for Monday, April 29th are rescheduled for Monday, May 6th.

#build config
server: true
auto: true
markdown: rdiscount 
